name: Run

on:
  # Escape clause to run the script manually if the cron fails to run.
  workflow_dispatch:
  schedule:
    # Timezone is in UTC, intentionally set like this to prevent queueing with many other
    # cron schedules. GitHub itself does not recommended using this cron setting if you want a guarantee that the job
    # is really run on that perfect schedule. This time is 23:30 Europe/Sofia (UTC+2/UTC+3).
    - cron: "30 21 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TZ: "Europe/Sofia"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v4

      - name: Set up system timezone
        run: |
          sudo timedatectl set-timezone ${{ env.TZ }}
          timedatectl

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install all dependencies
        run: uv sync --no-dev

      - name: Execute Python script
        run: uv run main.py
        env:
          DUOLINGO_USERNAME: ${{ secrets.DUOLINGO_USERNAME }}
          DUOLINGO_PASSWORD: ${{ secrets.DUOLINGO_PASSWORD }}
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}

      - name: Set commit message as environment variable
        run: |
          NOW=$(date '+%Y-%m-%d')
          echo "COMMIT_MESSAGE=auto: Duolingo status as of $NOW" >> $GITHUB_ENV

      - name: Commit changes and push them to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "data"
          author_name: ${{ secrets.GIT_AUTHOR_NAME }}
          author_email: ${{ secrets.GIT_AUTHOR_EMAIL }}
          message: ${{ env.COMMIT_MESSAGE }}

      - name: Build website
        run: |
          mkdir build
          cp web/* build
          mkdir -p build/data
          cp data/duolingo-progress.json build/data/
          cp data/duojson-profile.json build/data/ 2>/dev/null || echo "DuoJSON data not available"
          # Inject username into HTML files
          sed -i "s/DUOLINGO_USERNAME_PLACEHOLDER/${{ secrets.DUOLINGO_USERNAME }}/g" build/*.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
